### ISSUE TITLE
[Main Menu] Saltea la selección de nivel

### ISSUE THREAD

**Issue by ivanfernandez00** [fedepvg/Lintu#1]
Al presionar Play el juego se saltea la pantalla de selección del nivel e inicia directamente el Nivel 1.

Pasos de reproducción:
- Abrir juego
- Presionar Play

Resultado: El juego comienza directamente.
Frecuencia de reproducción: 2/10

Video: https://drive.google.com/open?id=1aKkmObmuEuolEIiKSYOnVRzvuoaXnkR_

**Comment by fedepvg** [comment]
Este bug es el mismo que #4 y #6 . No se van a arreglar ya que dependen de DS4 y el juego soporta control de ps4 y otros de forma nativa, por lo tanto no se necesita una herramienta externa
