### ISSUE TITLE
[A-Phase] No se abre el menú de pausa

### ISSUE THREAD

**Issue by ivanfernandez00** [fedepvg/Lintu#4]
Al presionar "Options"/"Start" en el control el menu de pausa se se mantiene abierto en el tiempo en el que se mantenga dicho botón, otra manera de mantenerlo abierto es precionando "ESC" en el teclado.

Pasos de reproducción:
1- Elegir un nivel
2- Presionar Start

Resultado: Se abre Options Menu por un instante.
Frecuencia de reproducción: 5/5
Video: https://drive.google.com/open?id=14cpNFNwbH9v33yce_5Kpq5J4XVQx2xXe

**Comment by fedepvg** [comment]
Hay algún otro paso para reproducir el error que puedas estar salteando? Porque yo no lo puedo reproducir

**Comment by ivanfernandez00** [comment]
Simplemente toco Start y el menú de pausa se mantiene abierto el tiempo en que yo mantengo apretado. Estoy usando un Dualshock 4 que lo conecto con el programa DS4 Windows. Tal vez pasa con este periférico nada más? Habría que ver si ese es el problema.
