### ISSUE TITLE
[A-Phase] Cursor con sombra

### ISSUE THREAD

**Issue by ivanfernandez00** [fedepvg/Lintu#5]
Durante el juego el cursor (la mira del personaje) tiene una sombra circular que se ve sobre los objetos a los que se apunta.

Pasos de reproducción:
1- Elegir un nivel
Resultado: en la "mira" del jugador se verá una sombra.
Frecuencia de reproducción: 5/5
Video: https://drive.google.com/open?id=1p0yZPSNRkqw0cT6lr48ni1pAe9lxDW8-

**Comment by fedepvg** [comment]
En linea con #9 , ya no esta la sombra tampoco
