### ISSUE TITLE
[A-Phase] Visualización de estela

### ISSUE THREAD

**Issue by ivanfernandez00** [fedepvg/Lintu#9]
En el nivel 2 el personaje no deja una estela como en el primer nivel.

Pasos de reproducción:
1- Seleccionar el nivel 2

Resultado: El personaje no tendrá estela.
Frecuencia de reproducción: 5/5
Video: https://drive.google.com/open?id=1HiCFAWHz0OySDwmI68uR47YLw-oIGmro

**Comment by fedepvg** [comment]
La estela era un feature que se elimino del juego, por lo tanto ya no existe tal bug
